/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Excepciones.DatoNoValido;
import Excepciones.DatoObligatorio;
import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import t7p01ej03.T7P01EJ03;

/**
 *
 * @author unai diez
 */
public class alumnos extends javax.swing.JFrame {

    /**
     * Creates new form alumnos
     */
    public alumnos() {
        initComponents();
// Centrar la ventana
        setLocationRelativeTo(null);
        // Ocultar etiqueta
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jdni = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        japellidos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jcurso = new javax.swing.JTextField();
        Aceptar = new javax.swing.JToggleButton();
        Salir = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Dni");

        jLabel2.setText("Nombre");

        jnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnombreActionPerformed(evt);
            }
        });

        jLabel3.setText("Apellidos");

        japellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                japellidosActionPerformed(evt);
            }
        });

        jLabel4.setText("Curso");

        Aceptar.setText("Aceptar");

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(85, 85, 85)
                                .addComponent(jcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(98, 98, 98)
                                .addComponent(jdni, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(japellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 76, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(Aceptar)
                .addGap(79, 79, 79)
                .addComponent(Salir)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(japellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aceptar)
                    .addComponent(Salir))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void japellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_japellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_japellidosActionPerformed

    private void jnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnombreActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new alumnos().setVisible(true);
            }
        });
    }
private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {                                         
    // Caja en la que colocar el cursor
    JTextField problema = null;
    try{
         // Validaciones que puede hacer la ventana
         // Validar el nombre
         if (jnombre.getText().isEmpty())
         {
             jnombre.setBackground(Color.red);
             problema = jnombre;
             throw new DatoObligatorio(1);
         }
         else
             if (jnombre.getBackground()== Color.red)
                  jnombre.setBackground(Color.white);
         
         // Si no está vacío compruebo que tiene un formato adecuado.
         Pattern patron = Pattern.compile("^[A-Z][a-z]+( [A-Z][a-z]+)*$");
         Matcher m = patron.matcher(jnombre.getText());
         if (!m.matches()){
             problema = jnombre;
             throw new DatoNoValido(1);
         }
         
         // Validar apellidos
         if (japellidos.getText().isEmpty())
         {
             
             problema = japellidos;
             throw new DatoObligatorio(2);
         }
         else
         
            
         
         // Si no está vacío compruebo que tiene un formato adecuado.
         patron = Pattern.compile("^[A-Z][a-z]+( [A-Z][a-z]+)+$");
         m = patron.matcher(japellidos.getText());
         if (!m.matches()){
             problema = japellidos;
             throw new DatoNoValido(2);
         }
         
         // Validamos el dni
         if (jdni.getText().isEmpty())
         {
             problema = jdni;
             throw new DatoObligatorio(3);
         }
         if (!validarFormatoDni())
         {
             jdni.selectAll();
             problema = jdni;
             throw new DatoNoValido(3);
         }
          
          // Validar con "base de datos"
         if (!T7P01EJ03.validarDni(jdni.getText())){
             problema = jdni;
             throw new DatoNoValido(4);
         }
         // Validamos el dni
         if (jcurso.getText().isEmpty())
         {
             problema = jcurso;
             throw new DatoObligatorio(3);
         }
         if (!validarFormatoDni())
         {
             jcurso.selectAll();
             problema = jcurso;
             throw new DatoNoValido(3);
         }
          

         // = tenDatosaltaPersona
         boolean alta = T7P01EJ03.altaalumno(jnombre.getText(),japellidos.getText(),jdni.getText(),jcurso.getText());
         if (alta)
         {
             JOptionPane.showMessageDialog(this,"Persona dada de alta");
             limpiarVentana();
         }
         else
             throw new Exception();
         
     }
     catch(DatoObligatorio e)
     {
         JOptionPane.showMessageDialog(this,e.getMessage());
         problema.requestFocus();
     }
     catch(DatoNoValido e)
     {
         JOptionPane.showMessageDialog(this,e.getMessage());
         problema.requestFocus();
     }
     catch(Exception e)
     {
         JOptionPane.showMessageDialog(this,"Problemas \n" + e.getMessage());
     }
}                                        

public boolean validarFormatoDni(){
   // Falta lo de %23
   String dniRegexp = "^[0-9]{8}[A-HJ-NP-TV-Z]$";
   return Pattern.matches(dniRegexp, jdni.getText());
}
public void limpiarVentana(){
    jnombre.setText("");
    japellidos.setText("");
    jdni.setText(null);
    jcurso.setText("");
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Aceptar;
    private javax.swing.JToggleButton Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField japellidos;
    private javax.swing.JTextField jcurso;
    private javax.swing.JTextField jdni;
    private javax.swing.JTextField jnombre;
    // End of variables declaration//GEN-END:variables
}
