/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.Proveedor;
import Constructor.T7P03EJ01;
import Excepciones.*;
import java.lang.reflect.Constructor;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author unai diez
 */
public class Tienda extends javax.swing.JFrame {
 private int unidades;
 private Double precio;
    public void limpiar() {
    }

    public void meter(ArrayList<Proveedor> proveedor, int y) {
        for(int x=0;x<proveedor.size();x++)
        cbProveedor.insertItemAt(proveedor.get(x).getProveedor(),x);
    }
    public Tienda() {
        initComponents();
        txtNombreprod.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bCompraventa = new javax.swing.ButtonGroup();
        Almacen = new javax.swing.JLabel();
        Nombreprod = new javax.swing.JLabel();
        Unidades = new javax.swing.JLabel();
        txtNombreprod = new javax.swing.JTextField();
        txtUnidades = new javax.swing.JTextField();
        Operacion = new javax.swing.JPanel();
        rbCompra = new javax.swing.JRadioButton();
        rbVenta = new javax.swing.JRadioButton();
        DCompra = new javax.swing.JPanel();
        Preciocompra = new javax.swing.JLabel();
        Proveedor = new javax.swing.JLabel();
        Importecompra = new javax.swing.JLabel();
        txtPreciocompra = new javax.swing.JTextField();
        txtImportecompra = new javax.swing.JTextField();
        cbProveedor = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        Precioventa = new javax.swing.JLabel();
        Cliente = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cbVolumen = new javax.swing.JCheckBox();
        cbPronto = new javax.swing.JCheckBox();
        Importeventa = new javax.swing.JLabel();
        txtImporteventa = new javax.swing.JTextField();
        txtPrecioventa = new javax.swing.JTextField();
        txtCliente = new javax.swing.JTextField();
        bAceptar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Almacen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Almacen.setText("Almacen");

        Nombreprod.setText("Nombre del producto");

        Unidades.setText("Unidades");

        txtNombreprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreprodActionPerformed(evt);
            }
        });

        txtUnidades.setEnabled(false);
        txtUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnidadesActionPerformed(evt);
            }
        });

        Operacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operacion a contabilizar", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 255))); // NOI18N

        bCompraventa.add(rbCompra);
        rbCompra.setText("Compra");
        rbCompra.setEnabled(false);
        rbCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCompraActionPerformed(evt);
            }
        });

        bCompraventa.add(rbVenta);
        rbVenta.setText("Venta");
        rbVenta.setEnabled(false);
        rbVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OperacionLayout = new javax.swing.GroupLayout(Operacion);
        Operacion.setLayout(OperacionLayout);
        OperacionLayout.setHorizontalGroup(
            OperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OperacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbCompra)
                .addGap(18, 18, 18)
                .addComponent(rbVenta)
                .addContainerGap(196, Short.MAX_VALUE))
        );
        OperacionLayout.setVerticalGroup(
            OperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OperacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCompra)
                    .addComponent(rbVenta))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        DCompra.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos sobre la compra", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N

        Preciocompra.setText("Precio");

        Proveedor.setText("Proveedor");

        Importecompra.setText("Importe de la compra:");

        txtPreciocompra.setEnabled(false);
        txtPreciocompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPreciocompraActionPerformed(evt);
            }
        });

        txtImportecompra.setEnabled(false);

        cbProveedor.setEnabled(false);
        cbProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DCompraLayout = new javax.swing.GroupLayout(DCompra);
        DCompra.setLayout(DCompraLayout);
        DCompraLayout.setHorizontalGroup(
            DCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DCompraLayout.createSequentialGroup()
                        .addComponent(Importecompra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtImportecompra, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DCompraLayout.createSequentialGroup()
                        .addComponent(Preciocompra)
                        .addGap(33, 33, 33)
                        .addComponent(txtPreciocompra, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(DCompraLayout.createSequentialGroup()
                        .addComponent(Proveedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(248, 248, 248))
        );
        DCompraLayout.setVerticalGroup(
            DCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Preciocompra)
                    .addComponent(txtPreciocompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Proveedor)
                    .addComponent(cbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(DCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Importecompra)
                    .addComponent(txtImportecompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos sobre la venta", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N

        Precioventa.setText("Precio");

        Cliente.setText("Cliente");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descuentos", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N

        cbVolumen.setText("Por Volumen");

        cbPronto.setText("Por pronto pago");
        cbPronto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProntoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbVolumen)
                .addGap(10, 10, 10)
                .addComponent(cbPronto)
                .addContainerGap(289, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbVolumen)
                    .addComponent(cbPronto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Importeventa.setText("Importe de la venta:");

        txtImporteventa.setEnabled(false);

        txtPrecioventa.setEnabled(false);

        txtCliente.setEnabled(false);
        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Importeventa)
                        .addGap(18, 18, 18)
                        .addComponent(txtImporteventa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Precioventa)
                            .addComponent(Cliente))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrecioventa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Precioventa)
                    .addComponent(txtPrecioventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cliente)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Importeventa)
                    .addComponent(txtImporteventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bAceptar.setText("Aceptar");
        bAceptar.setEnabled(false);
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(Almacen))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Operacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Nombreprod)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombreprod, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Unidades)
                                .addGap(74, 74, 74)
                                .addComponent(txtUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(DCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(bAceptar)
                        .addGap(93, 93, 93)
                        .addComponent(bCancelar)))
                .addContainerGap(274, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Almacen)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombreprod)
                    .addComponent(txtNombreprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Unidades))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Operacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAceptar)
                    .addComponent(bCancelar))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreprodActionPerformed
       try{
           if(txtNombreprod.getText().isEmpty())
               throw new DatoNoValido("El nombre del producto es un campo obligatorio");
        
        if (!T7P03EJ01.validarProducto(txtNombreprod.getText()))
           throw new DatoNoValido("El producto indicado no existe");
        
         txtNombreprod.setEnabled(false);
        txtUnidades.setEnabled(true);
        txtUnidades.requestFocus();   
          
       } catch(DatoNoValido e){
      JOptionPane.showMessageDialog(this,e.getMessage());
      txtNombreprod.requestFocus(); 
   }
   catch(Exception e){
       JOptionPane.showMessageDialog(this,e.getMessage());
       txtNombreprod.requestFocus();
   }
     
       
        
        
    }//GEN-LAST:event_txtNombreprodActionPerformed

    private void txtUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnidadesActionPerformed
        try{
           if(txtUnidades.getText().isEmpty())
               throw new DatoNoValido("El nombre del producto es un campo obligatorio");
        
         unidades=Integer.parseInt(txtUnidades.getText());
       txtUnidades.setEnabled(false);
        rbCompra.setEnabled(true);
        rbCompra.requestFocus();
        rbVenta.setEnabled(true);  
          
       } catch(DatoNoValido e){
      JOptionPane.showMessageDialog(this,e.getMessage());
      txtUnidades.requestFocus(); 
   }
        catch(NumberFormatException e){
       JOptionPane.showMessageDialog(this,"Las unidades son un dato numérico");
       txtUnidades.requestFocus();
   }
   catch(Exception e){
       JOptionPane.showMessageDialog(this,e.getMessage());
       txtUnidades.requestFocus();
   }
        
        
    }//GEN-LAST:event_txtUnidadesActionPerformed

    private void cbProntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProntoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbProntoActionPerformed

    private void cbProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProveedorActionPerformed
       
        cbProveedor.setEnabled(false);
         txtImportecompra.setText(contaprecio(txtUnidades.getText(),txtPreciocompra.getText()));  
         bAceptar.setEnabled(true);
       
    bAceptar.requestFocus();
    }//GEN-LAST:event_cbProveedorActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Quieres contabilizar otra operación?","opciones",JOptionPane.YES_NO_OPTION);
        if(respuesta==0)
        T7P03EJ01.volverEmpezar();
        else
        T7P03EJ01.Salir();   
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
      
           if(!txtImportecompra.getText().equals(""))
          JOptionPane.showMessageDialog(null, "producto comprado");
           else
          JOptionPane.showMessageDialog(null, "producto vendido"); 
            bCancelar.doClick();
       
    }//GEN-LAST:event_bAceptarActionPerformed

    private void rbCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCompraActionPerformed
         rbCompra.setEnabled(false);
            rbVenta.setEnabled(false);   
        txtPreciocompra.setEnabled(true);
        txtPreciocompra.requestFocus();
         txtCliente.setEnabled(false);
    }//GEN-LAST:event_rbCompraActionPerformed

    private void rbVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVentaActionPerformed
            rbCompra.setEnabled(false);
            rbVenta.setEnabled(false);
            txtPrecioventa.setText( T7P03EJ01.obtenerprecio());
            txtCliente.setEnabled(true);
            txtCliente.requestFocus();
         txtPreciocompra.setEnabled(false);
           
       
    }//GEN-LAST:event_rbVentaActionPerformed

    private void txtPreciocompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPreciocompraActionPerformed
        txtPreciocompra.setEnabled(false);
        
        cbProveedor.setEnabled(true);
        T7P03EJ01.proveedorproducto(txtNombreprod.getText());
    }//GEN-LAST:event_txtPreciocompraActionPerformed

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
try
{
       if (txtCliente.getText().isEmpty())
           throw new DatoNoValido("El nombre del cliente es un campo obligatorio");

       txtCliente.setEditable(false);
       cbPronto.setEnabled(true);
       cbVolumen.setEnabled(true);
       txtCliente.setText(String.valueOf(T7P03EJ01.calcularImporteVenta(unidades,cbPronto.isSelected(),cbVolumen.isSelected())));
       cbPronto.requestFocus();
       bAceptar.setEnabled(true);
   }
   catch(DatoNoValido e)
   {
      JOptionPane.showMessageDialog(this,e.getMessage());
   }
   catch(Exception e)
   {
       javax.swing.JOptionPane.showMessageDialog(this,e.getMessage());
   }
    }//GEN-LAST:event_txtClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tienda().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Almacen;
    private javax.swing.JLabel Cliente;
    private javax.swing.JPanel DCompra;
    private javax.swing.JLabel Importecompra;
    private javax.swing.JLabel Importeventa;
    private javax.swing.JLabel Nombreprod;
    private javax.swing.JPanel Operacion;
    private javax.swing.JLabel Preciocompra;
    private javax.swing.JLabel Precioventa;
    private javax.swing.JLabel Proveedor;
    private javax.swing.JLabel Unidades;
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bCancelar;
    private javax.swing.ButtonGroup bCompraventa;
    private javax.swing.JCheckBox cbPronto;
    private javax.swing.JComboBox<String> cbProveedor;
    private javax.swing.JCheckBox cbVolumen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rbCompra;
    private javax.swing.JRadioButton rbVenta;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtImportecompra;
    private javax.swing.JTextField txtImporteventa;
    private javax.swing.JTextField txtNombreprod;
    private javax.swing.JTextField txtPreciocompra;
    private javax.swing.JTextField txtPrecioventa;
    private javax.swing.JTextField txtUnidades;
    // End of variables declaration//GEN-END:variables

    private String contaprecio(String cantidad, String coste) {
        if(!cantidad.isEmpty() && !coste.isEmpty())
        unidades= Integer.parseInt(cantidad);
        precio= Double.parseDouble(coste);
       return String.valueOf(Math.rint((unidades * precio)*100)/100);
        }
}
