/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Main.Controlador;
import PersistenciaUML.*;
import bdpersistencia.exceptions.NonexistentEntityException;
import java.sql.Time;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author unai diez
 */
public class Inicio extends javax.swing.JFrame {
private Evento evento;
    private int opciones=0;
    public Inicio() {
        initComponents();
        limpio(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datePicker1 = new com.github.lgooddatepicker.components.DatePicker();
        jToolBar1 = new javax.swing.JToolBar();
        bGuardar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        bModificar = new javax.swing.JButton();
        bAsistir = new javax.swing.JButton();
        bListar = new javax.swing.JButton();
        jNombre = new javax.swing.JLabel();
        jDireccion = new javax.swing.JLabel();
        jHoraini = new javax.swing.JLabel();
        jHorafin = new javax.swing.JLabel();
        jAforo = new javax.swing.JLabel();
        txtNombre = new javax.swing.JFormattedTextField();
        txtDireccion = new javax.swing.JFormattedTextField();
        txtAforo = new javax.swing.JFormattedTextField();
        bCommit = new javax.swing.JButton();
        jFecha = new javax.swing.JLabel();
        txtFecha = new com.github.lgooddatepicker.components.DatePicker();
        txtHoraini = new com.github.lgooddatepicker.components.TimePicker();
        txtHorafin = new com.github.lgooddatepicker.components.TimePicker();
        jA1 = new javax.swing.JScrollPane();
        txtLista = new javax.swing.JTextArea();
        jNombrepersona = new javax.swing.JLabel();
        txtNombrepersona = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        jDNI = new javax.swing.JLabel();
        jEmpresa = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        jTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        cbEvento = new javax.swing.JComboBox<>();
        jEvento = new javax.swing.JLabel();
        jNif = new javax.swing.JLabel();
        txtNif = new javax.swing.JTextField();
        jCnae = new javax.swing.JLabel();
        txtCnae = new javax.swing.JTextField();
        txtRazon = new javax.swing.JTextField();
        jRazon = new javax.swing.JLabel();
        bBorrado = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mEvento = new javax.swing.JMenu();
        mGuardar = new javax.swing.JMenuItem();
        mCancelar = new javax.swing.JMenuItem();
        mModificar = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mAsistir = new javax.swing.JMenuItem();
        mListar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        bGuardar.setText("Guardar");
        bGuardar.setFocusable(false);
        bGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });
        jToolBar1.add(bGuardar);

        bCancelar.setText("Cancelar");
        bCancelar.setFocusable(false);
        bCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(bCancelar);

        bModificar.setText("Modificar");
        bModificar.setFocusable(false);
        bModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });
        jToolBar1.add(bModificar);

        bAsistir.setText("Asistir");
        bAsistir.setFocusable(false);
        bAsistir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bAsistir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bAsistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAsistirActionPerformed(evt);
            }
        });
        jToolBar1.add(bAsistir);

        bListar.setText("Listar");
        bListar.setFocusable(false);
        bListar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bListar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListarActionPerformed(evt);
            }
        });
        jToolBar1.add(bListar);

        jNombre.setText("Nombre");

        jDireccion.setText("Direccion");

        jHoraini.setText("Hora inicio");

        jHorafin.setText("Hora fin");

        jAforo.setText("Aforo");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });

        txtAforo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAforoActionPerformed(evt);
            }
        });

        bCommit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCommitActionPerformed(evt);
            }
        });

        jFecha.setText("Fecha");

        txtLista.setColumns(20);
        txtLista.setRows(5);
        jA1.setViewportView(txtLista);

        jNombrepersona.setText("Nombre");

        txtNombrepersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrepersonaActionPerformed(evt);
            }
        });

        txtDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniActionPerformed(evt);
            }
        });

        jDNI.setText("DNI");

        jEmpresa.setText("Empresa");

        txtEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpresaActionPerformed(evt);
            }
        });

        jTelefono.setText("Telefono");

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });

        cbEvento.setToolTipText("");
        cbEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEventoActionPerformed(evt);
            }
        });

        jEvento.setText("Evento");

        jNif.setText("NIF");

        txtNif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNifActionPerformed(evt);
            }
        });

        jCnae.setText("CNAE");

        txtCnae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCnaeActionPerformed(evt);
            }
        });

        txtRazon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRazonActionPerformed(evt);
            }
        });

        jRazon.setText("Razon social");

        bBorrado.setText("Cancelar");
        bBorrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorradoActionPerformed(evt);
            }
        });

        mEvento.setText("Eventos");
        mEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEventoActionPerformed(evt);
            }
        });

        mGuardar.setText("Guardar");
        mGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mGuardarActionPerformed(evt);
            }
        });
        mEvento.add(mGuardar);

        mCancelar.setText("Cancelar");
        mCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCancelarActionPerformed(evt);
            }
        });
        mEvento.add(mCancelar);

        mModificar.setText("Modificar");
        mModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mModificarActionPerformed(evt);
            }
        });
        mEvento.add(mModificar);

        jMenuBar1.add(mEvento);

        jMenu1.setText("Asistencias a eventos");

        mAsistir.setText("Asistir");
        mAsistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAsistirActionPerformed(evt);
            }
        });
        jMenu1.add(mAsistir);

        mListar.setText("Ver asistentes");
        mListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mListarActionPerformed(evt);
            }
        });
        jMenu1.add(mListar);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jA1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(43, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                            .addComponent(jHoraini)
                            .addComponent(jAforo)
                            .addComponent(jFecha)
                            .addComponent(jNombrepersona)
                            .addComponent(jDNI)
                            .addComponent(jEmpresa)
                            .addComponent(jEvento)
                            .addComponent(jNif)
                            .addComponent(jRazon))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtNif, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCnae)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtCnae, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(jTelefono)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTelefono))
                                    .addComponent(txtEmpresa)
                                    .addComponent(txtNombre)
                                    .addComponent(txtDireccion)
                                    .addComponent(txtFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtAforo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtHoraini, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jHorafin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(txtHorafin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(txtNombrepersona))
                                .addGap(161, 161, 161))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtRazon)
                                    .addComponent(cbEvento, 0, 350, Short.MAX_VALUE))
                                .addContainerGap(166, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(bCommit, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(bBorrado, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFecha)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHoraini)
                    .addComponent(jHorafin)
                    .addComponent(txtHoraini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHorafin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAforo)
                    .addComponent(txtAforo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNombrepersona)
                    .addComponent(txtNombrepersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDNI)
                    .addComponent(jTelefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEmpresa))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNif)
                    .addComponent(txtNif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCnae)
                    .addComponent(txtCnae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRazon)
                    .addComponent(txtRazon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEvento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bCommit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBorrado))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        mGuardar.doClick();
    }//GEN-LAST:event_bGuardarActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
         mCancelar.doClick();
       
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
         mModificar.doClick();
        
    }//GEN-LAST:event_bModificarActionPerformed

    private void bCommitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCommitActionPerformed
      if(bCommit.getText().equals("Guardar")){
          evento=new Evento(txtNombre.getText(),txtDireccion.getText(),conversionDate(txtFecha.getDate()),conversionTime(txtHoraini.getTime()),conversionTime(txtHorafin.getTime()),Integer.parseInt(txtAforo.getText()));
          try {
              Controlador.insertarevento(evento);
          } catch (Exception ex) {
              Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
          }
          
      }
      if(bCommit.getText().equals("Cancelar")){
          try {
              Controlador.cancelararevento(txtNombre.getText());
          
          } catch (bdperss.exceptions.NonexistentEntityException ex) {
              Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
          }
      }
      if(bCommit.getText().equals("Modificar")){
          try {
              Controlador.modificarevento(txtNombre.getText(),txtDireccion.getText(),txtFecha.getDate(),txtHoraini.getTime(),txtHorafin.getTime(),Integer.parseInt(txtAforo.getText()));
          } catch (Exception ex) {
              Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
          }
      }
      if(bCommit.getText().equals("Asistir")){
          try {
              if(!Controlador.buscarempresa(txtEmpresa.getText()))
                  Controlador.insertarempresa(txtEmpresa.getText(),txtNif.getText(),txtCnae.getText(),txtRazon.getText());            
              Controlador.insertarpersona(txtNombrepersona.getText(),txtDni.getText(),txtTelefono.getText(),txtNif.getText(),cbEvento.getSelectedItem().toString());
          } catch (Exception ex) {
              Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
          }
      }
      limpio(0);
    }//GEN-LAST:event_bCommitActionPerformed

    private void mEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mEventoActionPerformed

    private void mGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mGuardarActionPerformed
        limpio(0);
        bCommit.setText("Guardar");
        opciones=1;
        limpio(opciones);
    }//GEN-LAST:event_mGuardarActionPerformed

    private void mCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCancelarActionPerformed
       limpio(0);
         bCommit.setText("Cancelar");
       opciones=2;
        limpio(opciones);
    }//GEN-LAST:event_mCancelarActionPerformed

    private void mModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mModificarActionPerformed
        limpio(0);
         bCommit.setText("Modificar");
        opciones=3;
        limpio(opciones);
    }//GEN-LAST:event_mModificarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
       
        switch(opciones){
           case 1 :
        txtDireccion.setEnabled(true);
        txtDireccion.requestFocus();
        txtNombre.setEnabled(false);
               break;
           case 2:
               
        evento = Controlador.buscarevento(txtNombre.getText()) ;  
         if(evento != null)
        bCommit.setEnabled(true);
                break;
           case 3:  
         evento = Controlador.buscarevento(txtNombre.getText()); 
        if(evento != null){
        txtDireccion.setEnabled(true);
        txtDireccion.setText(evento.getDireccion());
        txtFecha.setEnabled(true);
        txtFecha.setDate(pasardato(evento.getFecha()));
        txtHoraini.setEnabled(true);
        txtHoraini.setText(pasarhora(evento.getHoraInicio()));
        txtHorafin.setEnabled(true);
        txtHorafin.setText(pasarhora(evento.getHoraFin()));
        txtAforo.setEnabled(true);
        txtAforo.setText(Integer.toString(evento.getMaxPersonas()));
        bCommit.setEnabled(true); }
                break;
          
                case 5 :
        evento = Controlador.buscarevento(txtNombre.getText()) ;  
         if(evento == null) {
        } else {            
             bCommit.setEnabled(true);
        }
                break;
        }
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        if(opciones==1){
        txtDireccion.setEnabled(false);
        txtFecha.setEnabled(true);
        txtHoraini.setEnabled(true);
        txtHorafin.setEnabled(true);
        txtAforo.setEnabled(true);
        }
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtAforoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAforoActionPerformed
        if(opciones==1){
            if(txtHoraini.getTime()!= null && txtHorafin.getTime()!= null && txtFecha.getDate()!= null){
        txtAforo.setEnabled(false);
        bCommit.setEnabled(true);
        bCommit.requestFocus();}
        }
    }//GEN-LAST:event_txtAforoActionPerformed

    private void mListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mListarActionPerformed
       limpio(0);
        bCommit.setText("Salir");
        opciones=5;
        limpio(opciones);
    }//GEN-LAST:event_mListarActionPerformed

    private void txtNombrepersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrepersonaActionPerformed
        
        if (Controlador.buscarpersona(txtNombrepersona.getText()))
               {
                  txtDni.setText(Controlador.buscardatopersona(txtNombrepersona.getText(),1));
                  txtTelefono.setText(Controlador.buscardatopersona(txtNombrepersona.getText(),1));
               }
        else{
            txtDni.setEnabled(true);
            
       txtTelefono.setEnabled(true);
        }
        if(txtNombrepersona.getText()!= null && txtDni.getText()!= null && txtTelefono.getText()!= null){
       bCommit.setEnabled(true);
        }
    }//GEN-LAST:event_txtNombrepersonaActionPerformed

    private void txtEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpresaActionPerformed
      if(opciones ==4){ 
          
        if(Controlador.buscarempresa(txtEmpresa.getText()))
        {  
           txtNif.setText(Controlador.buscardatoempresa(txtEmpresa.getText(),1));
           txtCnae.setText(Controlador.buscardatoempresa(txtEmpresa.getText(),2));
           txtRazon.setText(Controlador.buscardatoempresa(txtEmpresa.getText(),3));
                bCommit.setEnabled(true);
        
        }
            else
        {
                txtNif.setEnabled(true);
                txtCnae.setEnabled(true);
                txtRazon.setEnabled(true);
        }
        }
    }//GEN-LAST:event_txtEmpresaActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
      if(relleno()){
       bCommit.setEnabled(true);
        }
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void bAsistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAsistirActionPerformed
        mAsistir.doClick();
    }//GEN-LAST:event_bAsistirActionPerformed

    private void bListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListarActionPerformed
       mListar.doClick();
    }//GEN-LAST:event_bListarActionPerformed

    private void mAsistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAsistirActionPerformed
        limpio(0);
       bCommit.setText("Asistir");
        opciones=4;
        limpio(opciones);
    }//GEN-LAST:event_mAsistirActionPerformed

    private void txtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniActionPerformed
       if(relleno()){
       bCommit.setEnabled(true);
        }
    }//GEN-LAST:event_txtDniActionPerformed

    private void cbEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEventoActionPerformed
       if(opciones==4){
         if(relleno())
       bCommit.setEnabled(true);
        else
        {
           if(cbEvento.getSelectedIndex()!=-1) 
            Controlador.listarasistente(txtLista,cbEvento.getSelectedItem().toString());
        
        }     
        }
    }//GEN-LAST:event_cbEventoActionPerformed

    private void bBorradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorradoActionPerformed
       limpio(0);
    }//GEN-LAST:event_bBorradoActionPerformed

    private void txtNifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNifActionPerformed
        if(relleno()){
       bCommit.setEnabled(true);
        }
    }//GEN-LAST:event_txtNifActionPerformed

    private void txtCnaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCnaeActionPerformed
         if(relleno()){
       bCommit.setEnabled(true);
        }
    }//GEN-LAST:event_txtCnaeActionPerformed

    private void txtRazonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRazonActionPerformed
        if(relleno()){
       bCommit.setEnabled(true);
        }
    }//GEN-LAST:event_txtRazonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Inicio().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAsistir;
    private javax.swing.JButton bBorrado;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bCommit;
    private javax.swing.JButton bGuardar;
    private javax.swing.JButton bListar;
    private javax.swing.JButton bModificar;
    private javax.swing.JComboBox<String> cbEvento;
    private com.github.lgooddatepicker.components.DatePicker datePicker1;
    private javax.swing.JScrollPane jA1;
    private javax.swing.JLabel jAforo;
    private javax.swing.JLabel jCnae;
    private javax.swing.JLabel jDNI;
    private javax.swing.JLabel jDireccion;
    private javax.swing.JLabel jEmpresa;
    private javax.swing.JLabel jEvento;
    private javax.swing.JLabel jFecha;
    private javax.swing.JLabel jHorafin;
    private javax.swing.JLabel jHoraini;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel jNif;
    private javax.swing.JLabel jNombre;
    private javax.swing.JLabel jNombrepersona;
    private javax.swing.JLabel jRazon;
    private javax.swing.JLabel jTelefono;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mAsistir;
    private javax.swing.JMenuItem mCancelar;
    private javax.swing.JMenu mEvento;
    private javax.swing.JMenuItem mGuardar;
    private javax.swing.JMenuItem mListar;
    private javax.swing.JMenuItem mModificar;
    private javax.swing.JFormattedTextField txtAforo;
    private javax.swing.JTextField txtCnae;
    private javax.swing.JFormattedTextField txtDireccion;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtEmpresa;
    private com.github.lgooddatepicker.components.DatePicker txtFecha;
    private com.github.lgooddatepicker.components.TimePicker txtHorafin;
    private com.github.lgooddatepicker.components.TimePicker txtHoraini;
    private javax.swing.JTextArea txtLista;
    private javax.swing.JTextField txtNif;
    private javax.swing.JFormattedTextField txtNombre;
    private javax.swing.JTextField txtNombrepersona;
    private javax.swing.JTextField txtRazon;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    private void limpio(int i) {
      
        switch(i){
          
            case 1 :
       jNombre.setVisible(true);
       jDireccion.setVisible(true);
       jFecha.setVisible(true);
       jHoraini.setVisible(true);
       jHorafin.setVisible(true);
       jAforo.setVisible(true);
       bCommit.setVisible(true);
       bCommit.setEnabled(false);
       txtFecha.setVisible(true);
       txtNombre.setVisible(true);
       txtNombre.requestFocus();
       txtDireccion.setVisible(true);
       txtHoraini.setVisible(true);
       txtHorafin.setVisible(true);
       txtAforo.setVisible(true);
       txtNombre.setEnabled(true);
               break;
          
            
            case 2:   
       jNombre.setVisible(true);
       bCommit.setVisible(true);
       txtNombre.setVisible(true);
       txtNombre.setEnabled(true);
       txtNombre.requestFocus();
                break;
           
            
            case 3:  
       jNombre.setVisible(true);
       jDireccion.setVisible(true);
       jFecha.setVisible(true);
       jHoraini.setVisible(true);
       jHorafin.setVisible(true);
       jAforo.setVisible(true);
       bCommit.setVisible(true);
       bCommit.setEnabled(false);
       txtNombre.setVisible(true);
       txtDireccion.setVisible(true);
       txtFecha.setVisible(true);
       txtHoraini.setVisible(true);
       txtHorafin.setVisible(true);
       txtAforo.setVisible(true);
       txtNombre.setEnabled(true);
       txtNombre.requestFocus();
                break;
          
            
            case 4: 
        Controlador.listarevento(cbEvento);
       jNombrepersona.setVisible(true);
       jDNI.setVisible(true);
       jTelefono.setVisible(true);
       jEmpresa.setVisible(true);
       txtNombrepersona.setVisible(true);
       txtNombrepersona.setEnabled(true);
       txtDni.setVisible(true);
       
       txtTelefono.setVisible(true);
       txtEmpresa.setVisible(true);
       txtEmpresa.setEnabled(true); 
       jNif.setVisible(true);
       txtNif.setVisible(true);
       txtNif.setEnabled(false);
       jCnae.setVisible(true);
       txtCnae.setVisible(true);
       txtCnae.setEnabled(false);
       jRazon.setVisible(true);
       txtRazon.setVisible(true);
       txtRazon.setEnabled(false);
       jEvento.setVisible(true);
       cbEvento.setVisible(true);
       bCommit.setVisible(true);
       bCommit.setEnabled(false);
               break;
          
            
            case 5: 
      Controlador.listarevento2(cbEvento);
       jEvento.setVisible(true);
       cbEvento.setVisible(true);
       jA1.setVisible(true);
       txtLista.setVisible(true);
       txtLista.setEnabled(false);
       bCommit.setVisible(true);
               break;
          
            
            
            default:
        evento=new Evento();        
       jEvento.setVisible(false);
       cbEvento.setVisible(false);
       jNombre.setVisible(false);
       jDireccion.setVisible(false);
       jFecha.setVisible(false);
       jHoraini.setVisible(false);
       jHorafin.setVisible(false);
       jAforo.setVisible(false);
       bCommit.setVisible(false);
       txtNombre.setVisible(false);
       txtNombre.setEnabled(false);
       txtDireccion.setEnabled(false);
       txtHoraini.setEnabled(false);
       txtHorafin.setEnabled(false);
       txtAforo.setEnabled(false);
       txtNombre.setText("");
       txtDireccion.setText("");
       txtFecha.setText("");
       txtHoraini.setText("");
       txtHorafin.setText("");
       txtAforo.setText("");
       txtDireccion.setVisible(false);
       txtHoraini.setVisible(false);
       txtHorafin.setVisible(false);
       txtAforo.setVisible(false);
       txtFecha.setVisible(false);
       txtFecha.setEnabled(false);
       txtFecha.setText("");
       jNombrepersona.setVisible(false);
       jDNI.setVisible(false);
       jTelefono.setVisible(false);
       jEmpresa.setVisible(false);
       jA1.setVisible(false);
       txtLista.setVisible(false);
       txtLista.setEnabled(false);
       txtNombrepersona.setVisible(false);
       txtNombrepersona.setEnabled(false);
       txtNombrepersona.setText("");
       txtDni.setVisible(false);
       txtDni.setEnabled(false);
       txtDni.setText("");
       txtTelefono.setVisible(false);
       txtTelefono.setEnabled(false);
       txtTelefono.setText("");
       txtEmpresa.setVisible(false);
       txtEmpresa.setEnabled(false);
       txtEmpresa.setText("");
       jNif.setVisible(false);
       txtNif.setVisible(false);
       txtNif.setText("");
       jCnae.setVisible(false);
       txtCnae.setVisible(false);
       txtCnae.setText("");
       jRazon.setVisible(false);
       txtRazon.setVisible(false);
       txtRazon.setText("");
               break;
       }
       
    }

    private LocalDate pasardato(Date fecha) {
LocalDate paso=fecha.toInstant()
      .atZone(ZoneId.systemDefault())
      .toLocalDate();
        return paso;
    }

    private String pasarhora(Date hora) {
DateFormat dateFormat = new SimpleDateFormat("hh:mm:ss");  
String vuelta = dateFormat.format(hora);  
return vuelta;
    }
private static Time conversionTime(LocalTime hora) {
         return java.sql.Time.valueOf(hora); }

public static Date conversionDate(LocalDate fecha){
        // Conversion LocalDate en java.sql.Date
        return java.util.Date.from(fecha.atStartOfDay().atZone(ZoneId.systemDefault()).toInstant());
    }

    private boolean relleno() {
       if(
               txtNombrepersona.getText()!= null && 
               txtDni.getText()!= null && 
               txtTelefono.getText()!= null &&
               txtNif.getText()!= null &&
               txtCnae.getText()!= null &&
               txtRazon.getText()!= null &&
               cbEvento.getSelectedIndex()!=-1
               )
      return true;
      else
      return false;
       }
}
